// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoApi.SourceGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DomainFilterTemplate : DomainFilterTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nnamespace ");
            
            #line 9 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(" \n{\n    public static class ");
            
            #line 11 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("Filters\n    {\n");
            
            #line 13 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 foreach(var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("        public static IQueryable<");
            
            #line 14 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 14 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("Equals(this IQueryable<");
            
            #line 14 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 14 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n");
            
            #line 18 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 if(property.Type == "string") { 
            
            #line default
            #line hidden
            this.Write("\n        public static IQueryable<");
            
            #line 20 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 20 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("StartsWith(this IQueryable<");
            
            #line 20 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 20 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 25 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 25 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("EndsWith(this IQueryable<");
            
            #line 25 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 25 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 30 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 30 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("Contains(this IQueryable<");
            
            #line 30 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 30 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n");
            
            #line 34 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 35 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 if(property.Type == "int") { 
            
            #line default
            #line hidden
            this.Write("\n        public static IQueryable<");
            
            #line 37 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 37 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("Between(this IQueryable<");
            
            #line 37 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 37 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 42 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 42 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("GreaterThan(this IQueryable<");
            
            #line 42 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 42 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 47 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 47 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("LessThan(this IQueryable<");
            
            #line 47 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 47 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 52 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 52 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("GreaterThanOrEquals(this IQueryable<");
            
            #line 52 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 52 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 57 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 57 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("LessThanOrEquals(this IQueryable<");
            
            #line 57 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 57 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n");
            
            #line 61 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 62 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 if(property.Type == "long") { 
            
            #line default
            #line hidden
            this.Write("\n        public static IQueryable<");
            
            #line 64 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 64 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("Between(this IQueryable<");
            
            #line 64 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 64 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n\n        public static IQueryable<");
            
            #line 70 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 70 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("GreaterThan(this IQueryable<");
            
            #line 70 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 70 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 75 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 75 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("LessThan(this IQueryable<");
            
            #line 75 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 75 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 80 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 80 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("GreaterThanOrEquals(this IQueryable<");
            
            #line 80 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 80 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 85 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 85 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("LessThanOrEquals(this IQueryable<");
            
            #line 85 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 85 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n");
            
            #line 89 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 90 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 if(property.Type == "short") { 
            
            #line default
            #line hidden
            this.Write("\n        public static IQueryable<");
            
            #line 92 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 92 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("StartsWith(this IQueryable<");
            
            #line 92 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 92 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 97 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 97 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("EndsWith(this IQueryable<");
            
            #line 97 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 97 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 102 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 102 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("Contains(this IQueryable<");
            
            #line 102 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 102 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n");
            
            #line 106 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 107 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 if(property.Type == "datetime") { 
            
            #line default
            #line hidden
            this.Write("\n        public static IQueryable<");
            
            #line 109 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 109 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("StartsWith(this IQueryable<");
            
            #line 109 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 109 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 114 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 114 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("EndsWith(this IQueryable<");
            
            #line 114 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 114 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n\n        public static IQueryable<");
            
            #line 119 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> Where");
            
            #line 119 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("Contains(this IQueryable<");
            
            #line 119 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainEntityName));
            
            #line default
            #line hidden
            this.Write("> queryable, ");
            
            #line 119 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(" value)\n        {\n            return queryable;\n        }\n");
            
            #line 123 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 124 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\n}\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 127 "/Users/kasper/AutoApi/AutoApi.SourceGenerator/DomainFilterTemplate.tt"

    public string Namespace { get; set; }
    
    public string DomainEntityName { get; set; }
    
    public class Property
    {
        public string Field { get; set; }
        
        public string Name { get; set; }
        
        public string Type { get; set; }
    }

    public List<Property> Properties { get; } = new();

    public void AddProperty(string field, string name, string type) => Properties.Add(new Property()
    {
        Name = name,
        Field = field,
        Type = type
    });

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DomainFilterTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
